### ISSUE TITLE
画像アップスケール設定を開こうとするとエラーが出る

### ISSUE THREAD

**Issue by Anko777** [XyLe-GBP/waifu2x-ncnn-vulkan-GUI-Edition-Reloaded#5]
タイトル通りです。

使用環境は以下になります。
![NoName_2022-11-11_19-43-15_No-00](https://user-images.githubusercontent.com/33007409/201324129-94538cb0-5d53-4642-bebd-b2bc6d74c3ff.png)

エラー内容はこうなっております。
![NoName_2022-11-11_19-41-22_No-00](https://user-images.githubusercontent.com/33007409/201324240-5632fc3a-09af-412f-b5e6-8e0999eb9d24.png)

**Comment by XyLe-GBP** [comment]
今回のアップデートでコードの変更を行いました。
アプリケーションをアップデートして頂き、エラーが修正されているかどうかをご確認ください。
それでも依然、エラーが発生する場合はお手数ですがここに再度コメントをお願いします。
また、その際には「例外テキスト」の全部分をコピペ or スクショして併せてお送りください。
尚、エラーが解決した場合、コメントは不要です。よろしくお願いします。
