### ISSUE TITLE
8.3形式以外のファイル名でエラーが起きる(1.33.2220.1218-Beta)

### ISSUE THREAD

**Issue by thxalot** [XyLe-GBP/waifu2x-ncnn-vulkan-GUI-Edition-Reloaded#6]
1.33.2220.1218-Betaにおいて、8文字.3文字の形式以外のファイル名の画像を
入力(ドラッグ&ドロップ、ファイル→画像ファイルを開く のいずれの方法でも)
するとプレビューは正常に表示されるのですが、
「画像のアップスケーリング」をクリックすると変換の工程がすぐに終わり、
保存のダイアログが出るので「保存」をクリックすると
"Could not find file"というエラーダイアログが出ます。
同じ画像をコピーしてファイル名を変えてみると、以下のような結果となりました。

OK: 12345678.jpg
NG: 12345678.jpeg → テンポラリファイル 123456\~1.JPEは無いという内容のエラーが出て、終了させると元ファイル消滅
NG: 123456789.jpg → テンポラリファイル 123456\~1.pngは無いという内容のエラーが出る
NG: 123456789.jpeg → テンポラリファイル 123456\~2.JPEは無いという内容のエラーが出て、終了させると元ファイル消滅

恐れ入りますが、ご対応をお願いいたします。

OSはWindows 10 Pro 64bit 日本語 10.0.19045 [build: 19045] です。

**Comment by XyLe-GBP** [comment]
不具合のご報告誠にありがとうございます。
次回のアップデートで修正予定ですので、今しばらくお待ちいただけますと幸いです。
よろしくお願いいたします。

**Comment by XyLe-GBP** [comment]
エラーが発生したときの状況なのですが、"ハンドルされていない例外"というウインドウが出ますでしょうか？
もしも該当ウインドウが出るのでしたら、"例外テキスト"の部分をコピペかスクリーンショットしてここに添付していただけないでしょうか。

**Comment by thxalot** [comment]
横着をしてすみませんでした。ウィンドウのスクリーンショットとテキスト部分は以下の通りです。
なお、1.33.2220.1218-Betaを実行しているユーザー名はuser300で、ダウンロードしたファイルを
ダウンロードフォルダのwaifu2x-nvger-release_221218という名前のフォルダに解凍して
実行しています。user300はアドミニストレータ権限を持っています。

【12345678.jpegの場合】
![8_4](https://user-images.githubusercontent.com/30388369/208417671-b666a3dc-4fb7-4b58-9929-7bbb43a428d5.png)
[8_4.txt](https://github.com/XyLe-GBP/waifu2x-ncnn-vulkan-GUI-Edition-Reloaded/files/10258924/8_4.txt)

【123456789.jpgの場合】
![9_3](https://user-images.githubusercontent.com/30388369/208418474-9e8c6b78-53ed-459c-92f0-e3f391c8bebc.png)
[9_3.txt](https://github.com/XyLe-GBP/waifu2x-ncnn-vulkan-GUI-Edition-Reloaded/files/10258930/9_3.txt)

【123456789.jpegの場合】
![9_4](https://user-images.githubusercontent.com/30388369/208418659-52f02302-635e-499d-aa81-315a58c8b3fa.png)
[9_4.txt](https://github.com/XyLe-GBP/waifu2x-ncnn-vulkan-GUI-Edition-Reloaded/files/10258938/9_4.txt)

以上です。

**Comment by XyLe-GBP** [comment]
今回のアップデートで、問題に関するコード修正を行いました。
まだ不具合が治っていない場合は、お手数ですがここにコメントを残してください。
よろしくお願いします。
