### ISSUE TITLE
表示の問題(VRAM容量、dGPU非表示) (1.33.2220.1218-Beta)

### ISSUE THREAD

**Issue by thxalot** [XyLe-GBP/waifu2x-ncnn-vulkan-GUI-Edition-Reloaded#7]
1.33.2220.1218-Betaにて、複数の表示の問題があります。

1. VRAM容量が正しく表示されない
Intel Arc A770 (16GBメモリ)をThuderbolt 3外付けGPU BOXに取り付け、
IntelのNUC(RNUC12WSHI50000、メインメモリ32GB*2)に接続しています。
Windows 10 Pro 64bit 日本語のタスクマネージャーでは専用メモリ容量16.0GBと表示されるのですが、
waifu2x-nvger 1.33.2220.1218-Betaでは1024MiB RAMと表示されます。(添付画像をご参照ください)
A770で変換させると1GB以上のメモリを使用するので、表示だけの問題だと思われます。

2. dGPUが表示されない
上記の環境で「画像アップスケール設定」ダイアログの「基本」タブの
「使用するGPU」プルダウンメニューを表示させると、dGPUが表示されず、
「自動」が一つと「iGPU [Intel(R) Iris(R) Xe Graphics」が二つ表示され、dGPUが表示されません。
外付けGPU BOXを取り外しても表示は変わりません。
dGPU(A770)は、メインのウィンドウのプルダウンメニューで選択できますので
動作上は問題ないように思われます。

以上です。ご対応をよろしくお願い致します。
![VRAM](https://user-images.githubusercontent.com/30388369/208312569-d9c9fdab-fa93-455e-94bf-ade62d76790c.png)
![GPU](https://user-images.githubusercontent.com/30388369/208312574-a2bbac8c-7623-4669-bcd9-fc39bbb65f7e.png)

**Comment by thxalot** [comment]
GPU BOX内のビデオカードをGeForce GTX 1080Ti搭載のもの(11GBメモリ)に変えてみました。
VRAM容量は4095MiBと表示され、やはり実際の容量とは異なります。
しかし「使用するGPU」プルダウンメニューにはdGPUとしてGTX 1080Tiが表示されています。
残念ながら、AMDのdGPUは持っていないので確認できません。
![1080Ti](https://user-images.githubusercontent.com/30388369/208314584-0e0d4298-6e6e-406f-b1aa-a8782493cdf8.png)

**Comment by XyLe-GBP** [comment]
不具合のご報告誠にありがとうございます。
1. VRAM容量が正しく表示されない

この問題は既に認知しております。
これは、Win32_VideoControllerの4GBの制限によるものです。
Win32_VideoControllerのAdapterRAMを使用して情報を取得しているため、4GB以上のRAMが存在するビデオカードですと
上記の不具合が発生します。
(当方が使用している GTX 1070Ti (8GB)でも4095MiB RAMと表示されます。)
ビデオカードのRAM取得関連の実装を変更する予定ですのでお待ちください。

2. dGPUが表示されない

当方の環境に複数のGPUがないので、デバッグ不足になります。
お手数をおかけしますが、不具合が修正されるまでは"自動"を選択して変換して頂くか、GPUを1つにしてdGPUを選んで変換して頂けますと幸いです。

次回のアップデートで可能な限り修正予定ですので、今しばらくお待ちいただけますと幸いです。
よろしくお願いいたします。

**Comment by XyLe-GBP** [comment]
今回のアップデートで、関連するコード修正を行いました。
1.の問題は実装を変更したので、正しく動作するかどうかご確認お願いします。
2.の問題に関しましては当方の環境にIntel Arcがないため、期待する動作にならない可能性があります。
よろしくお願いします。

**Comment by thxalot** [comment]
返信が遅れましてすみません。
まず、2については正常に表示がされているようです。Intel Xeが二つ表示されることもなくなりました。

1については、容量の表示については直っているようです。
ただし、過去に接続されていて、現在は接続されていないGPU
(デバイスマネージャーで、「表示」→「非表示のデバイスの表示(W)」で、薄い色で表示されるデバイス)
が二つ表示され、現在接続されているGPUは表示されないという状態です。
「画像アップスケール設定」ウィンドウでdGPU(Intel Arc)を選択しても処理には使用されず、
iGPU(Intel Xe)が使用されます。

別件ですが、8.3形式ファイル名の件は直ったように思われますが、こちらも検証が不十分です。
(急にネットワーク設備の工事が入ってしまい、バタバタしておりまして……)
年明けには何とかなると思います。
PNGの16bpc対応(現状は8bpcのみですよね?)の要望を出そうと思っておりますので、
ご検討頂けましたら幸いです。

**Comment by XyLe-GBP** [comment]
検証いただきありがとうございます。
1.34にて、追加でGPU関連の不具合に関するコード修正を行いました。
1.34の詳細についてはリリースを参照ください。
なお画像については現状、PNGは32bit-RGBA、それ以外の形式では通常の形式(アルファチャンネル無し)で出力されます。
Magick.NETを使用しているため、Magick.NETが扱える形式であれば対応は可能です。
